### PR TITLE
Feature mumukit 2.7

### PR DESCRIPTION
**Pull request by flbulgarelli**
Updating ruby and mumukit version

### CODE REVIEW

**Comment by flbulgarelli** [comment]
@Charlyzzz please review and merge

**Comment by flbulgarelli** [comment]
@Charlyzzz sorry, I didn't get your last question :disappointed:

**Comment by Charlyzzz** [comment]
~~~ruby
<<WLK
     foo
WLK
~~~

**Comment by flbulgarelli** [comment]
@Charlyzzz you don't have to define it, you can simply use any character set to delimit HEREDOCs. Also, when using a well known language name - not like Wollok :stuck_out_tongue: - some IDEs color it automatically.

**Pull request merged**
